# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_frame', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
